shrimp_facts = [ "Shrimp are found in oceans, freshwater, and brackish water worldwide.",
    "They belong to the class Crustacea, making them relatives of lobsters and crabs.",
    "There are over 2,000 species of shrimp!",
    "Shrimp are typically omnivorous, eating algae, plankton, and detritus.",
    "The largest shrimp species, the tiger prawn, can grow up to 13 inches long!",
    "The smallest shrimp, the fairy shrimp, is only about 0.02 inches long.",
    "Most shrimp are transparent, allowing them to blend into their surroundings.",
    "Shrimp can swim backward by quickly flipping their tails.",
    "Their body is divided into two main parts: the cephalothorax (head and thorax) and the abdomen."
    "Shrimp have a hard exoskeleton that they shed as they grow.",
    "Shrimp have a fan-like tail that helps them move quickly in water.",
    "They breathe through gills, even in very low oxygen environments.",
    "A shrimp’s heart is located in its head!",
    "They have compound eyes that can detect polarized light.",
    "Shrimp are decapods, meaning they have ten legs.",
    "Shrimp legs are specialized—some are for walking, others for feeding.",
    "Their antennae can be longer than their body and are used for sensing.",
    "Shrimp can regenerate lost limbs or antennae.",
    "Their color is due to chromatophores, which can adjust pigmentation.",
    "Shrimp have a nervous system more similar to insects than fish.",
    "Some shrimp species are highly social and live in colonies.",
    "Shrimp communicate by releasing pheromones into the water.",
    "Certain shrimp species 'dance' to communicate with potential mates.",
    "Shrimp use their claws for defense and showing dominance.",
    "Many shrimp are nocturnal, hiding during the day and feeding at night.",
    "Some shrimp, like the cleaner shrimp, form mutualistic relationships by cleaning parasites from fish.",
    "Shrimp are territorial and will fight each other to protect their space.",
    "They’re excellent burrowers, creating shelters in the sand or mud.",
    "Shrimp often use their powerful tails to escape predators quickly.",
    "When threatened, they can emit a loud 'pop' with their claws or tail.",
    "The pistol shrimp can snap its claw to create a bubble that stuns prey.",
    "The snapping sound of a pistol shrimp can reach up to 218 decibels, louder than a gunshot!",
    "Mantis shrimp are known for their powerful, hammer-like claws, capable of breaking glass.",
    "Mantis shrimp have 16 color-receptive cones, compared to humans’ three, giving them incredible vision.",
    "The ghost shrimp is a burrowing species that looks almost invisible in water.",
    "The peppermint shrimp is known for its red-striped body and ability to eat pests in aquariums.",
    "Cherry shrimp are popular in aquariums for their bright red color.",
    "Amano shrimp are famous for controlling algae in tanks.",
    "The bumblebee shrimp has distinctive black and yellow stripes.",
    "The rock shrimp has a tough exoskeleton resembling that of a lobster.",
    "Most shrimp are hermaphroditic, starting life as males and later becoming females.",
    "Female shrimp carry fertilized eggs on their swimmerets (legs under their abdomen).",
    "Shrimp eggs hatch into tiny larvae that drift with plankton before maturing.",
    "A shrimp can produce up to 50,000 eggs in one spawning.",
    "Shrimp larvae undergo multiple molting stages before becoming adults.",
    "Depending on the species, shrimp can live from 1 to 7 years.",
    "Many shrimp species synchronize their breeding with the moon cycle.",
    "In some species, males attract females by performing 'courtship dances.'",
    "The bright coloration of some shrimp is often linked to mating displays.",
    "Shrimp are broadcast spawners, releasing eggs and sperm into the water column.",
    "Shrimp farming is a multi-billion-dollar industry globally.",
    "Over 9 million tons of shrimp are produced annually for human consumption.",
    "The most popular edible shrimp species is the whiteleg shrimp.",
    "Shrimp farming dates back over 1,000 years in Southeast Asia.",
    "Shrimp is one of the most widely consumed seafoods in the world.",
    "Shrimp shells are used to make chitin, which has industrial and medical applications.",
    "Shrimp are a key ingredient in dishes like paella, gumbo, and tempura.",
    "In Japan, ebi sushi (shrimp sushi) is highly prized.",
    "In Cajun culture, shrimp boils are a popular communal meal.",
    "Shrimp have been featured in art and mythology in many cultures, symbolizing abundance.",
    "Shrimp are a vital part of the marine food chain.",
    "They help recycle nutrients by feeding on detritus.",
    "Some shrimp species act as 'cleaners' for larger marine animals.",
    "Overfishing and unsustainable shrimp farming threaten wild populations.",
    "Mangroves are often destroyed to create shrimp farms, impacting biodiversity.",
    "Shrimp farming has a significant carbon footprint, especially when wild feed is used.",
    "Shrimp trawling often results in high levels of bycatch (unintended species).",
    "Sustainable shrimp farming practices are being developed to reduce ecological harm.",
    "Shrimp play a role in maintaining coral reef health.",
    "Some species of shrimp thrive in hydrothermal vents deep in the ocean.",
    "Shrimp can 'glow' in the dark due to bioluminescent bacteria on their bodies.",
    "The fastest shrimp is the mantis shrimp, with a claw strike speed of 23 m/s.",
    "Shrimp have been observed using tools, such as moving pebbles to build shelters.",
    "Some shrimp species can survive in volcanic sulfur pools.",
    "Shrimp eyes can adapt to low-light environments, enabling deep-sea living.",
    "Antarctic krill, a shrimp-like species, are one of the most abundant organisms on Earth.",
    "The shrimp’s muscle composition makes them incredibly strong for their size.",
    "Certain shrimp are bioindicators, signaling the health of marine ecosystems.",
    "Some shrimp 'farm' algae on their bodies for food.",
    "Shrimp can travel short distances on land if their environment dries up.",
    "Shrimp molt their exoskeletons as they grow, leaving behind 'ghost shells.'",
    "After molting, shrimp hide because their new exoskeleton is soft and vulnerable.",
    "Many aquarium shrimp thrive in planted tanks, which mimic their natural habitat.",
    "Shrimp are sensitive to water quality and require stable conditions.",
    "Overfeeding shrimp can lead to ammonia spikes in aquariums.",
    "Shrimp love hiding in crevices and caves.",
    "They enjoy grazing on biofilm and algae in tanks.",
    "Male shrimp are smaller and less colorful than females.",
    "Shrimp are social and thrive in groups known as 'colonies.'",
    "Some shrimp enthusiasts breed specific colors, like blue, orange, or yellow shrimp.",
    "Bubba Gump Shrimp Co. from Forrest Gump popularized shrimp culture.",
    "Shrimp are often featured in animated films like Finding Nemo (Jacques the cleaner shrimp).",
    "The term 'jumbo shrimp' is an oxymoron, as shrimp are small by nature.",
    "'Shrimping' is a term used for trawling small crustaceans in fishing.",
    "Shrimp-themed festivals, like the National Shrimp Festival in Alabama, are celebrated worldwide.",
    "The phrase 'shrimp on the barbie' became famous from an Australian tourism ad.",
    "Shrimp shells are used to create natural pigments for dyes.",
    "In Dungeons & Dragons, some campaigns feature giant shrimp-like monsters.",
    "Shrimp have inspired robotic designs due to their efficient movement in water.",
    "Shrimp memes often joke about their simplicity and cuteness."
]

used_shrimp_facts = []


burns = ["Your only talent is making everyone else look smarter by comparison",
    "You're the reason the gene pool needs a lifeguard",
    "You're the reason the average person believes in evolution",
    "You’re the human equivalent of a participation trophy",
    "Your mom",
    "You're the reason they invented double doors",
    "Darwin called- he wants his theory back",
    "You bring new meaning to the phrase “lowering the bar.”",
    "Ur gay",
    "You're the reason they put instructions on shampoo",
    "Your playlist probably starts with Nickelback",
    "The eyes see and the mouth moves but Mr. Brain has long since departed"
    ]

used_burns = []


jokes = ["Your momma so fat, when she goes camping, the bears hide their food.",
    "Your momma so fat, she brings a spoon to the Super Bowl.",
    "Your momma so fat, when she skips a meal, the stock market drops.",
    "Your momma so fat, her shadow has its own zip code.",
    "Your momma so fat, when she walks past the TV, you miss three episodes.",
    "Your momma so fat, she broke the stairway to heaven.",
    "Your momma so fat, her cereal bowl comes with a lifeguard.",
    "Your momma so fat, when she turns around, its her birthday again.",
    "Your momma so fat, when she wears a black dress, people think there's a solar eclipse.",
    "Yo mama so ugly, she made an onion cry",
    "Trampolines were called jumpolines before yo momma used them",
    "Your mother is a lovely woman and I have a great deal of respect for her",
    "The world was flat. Then they buried yo momma."
    ]

used_jokes = []