name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code and Restart
        run: |
          cd /home/bomb/Discord_Bot
          git reset --hard HEAD
          git pull origin main
          sudo systemctl restart discord-bot
